# Generated by Django 3.1.7 on 2021-04-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='JowiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category_id', models.IntegerField()),
                ('status', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'jowi_category',
            },
        ),
        migrations.CreateModel(
            name='JowiManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название ресторана')),
                ('jowi_id', models.CharField(max_length=255)),
                ('manufacturer_id', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'jowi_manufacturers',
            },
        ),
        migrations.CreateModel(
            name='JowiProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.CharField(max_length=255)),
                ('product_id', models.IntegerField()),
                ('jowi_category_id', models.IntegerField()),
                ('jowi_id', models.CharField(max_length=255)),
                ('notification', models.IntegerField(null=True)),
                ('modified', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'jowi_products',
            },
        )
    ]
